"""empty message

Revision ID: 781eed935141
Revises: 1f8fd5f6dca5
Create Date: 2019-02-12 13:17:07.966522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '781eed935141'
down_revision = '1f8fd5f6dca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
